version: '3'

services:

  service1:
    build:
      context: service1/
      tags:
        - "service1"
    ports:
      - 8001:80
    networks:
      - internal
    environment:
      SERVICE2: service2
    depends_on:
      - service2

  service2:
    build:
      context: service2/
      tags:
        - "service2"
    networks:
      - internal

networks:
  internal:
    name: internal